language: node_js

node_js:
  - lts/*

install: npm install

cache:
  directories:
    - node_modules

#branches:
#  only:
#    - master

script:
#  - npm run lint
#  - npm run test
  - npm run build

#before_deploy:
#  - cd $TRAVIS_BUILD_DIR

deploy:
#  provider: pages
#  cleanup: true
  provider: pages
  edge: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  keep_history: true
  on:
    branch: master

