language: node_js

node_js:
  - lts/*

install: npm install

cache:
  directories:
    - node_modules

script:
#  - npm run lint
#  - npm run test
  - npm run build

deploy:
  provider: pages
  edge: true
#  cleanup: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  keep_history: true
  on:
    branch: master

